export const testData = [
  {
    _id: '6526521e92477044832b89dc',
    index: 0,
    guid: 'cebf02bb-efca-4f8a-a0ab-1d00db014e74',
    isActive: false,
    balance: '$3,979.19',
    picture: 'http://placehold.it/32x32',
    age: 39,
    eyeColor: 'blue',
    name: 'Good Cameron',
    gender: 'male',
    company: 'COFINE',
    email: 'goodcameron@cofine.com',
    phone: '+1 (811) 549-3837',
    address: '142 Applegate Court, Denio, American Samoa, 9992',
    about:
      'Sit amet cupidatat nostrud anim nulla. Minim exercitation culpa eu mollit tempor non. Labore minim voluptate excepteur deserunt do consequat dolore culpa in. Incididunt cillum tempor nostrud cillum tempor labore aliquip adipisicing proident.\r\n',
    registered: '2020-12-10T03:49:16 -02:00',
    latitude: 1.672217,
    longitude: -38.178335,
    tags: ['tempor', 'eu', 'do', 'commodo', 'Lorem', 'occaecat', 'ex'],
    friends: [
      {
        id: 0,
        name: 'Walsh Cantrell',
      },
      {
        id: 1,
        name: 'Rojas Calderon',
      },
      {
        id: 2,
        name: 'Pansy Benson',
      },
    ],
    greeting: 'Hello, Good Cameron! You have 2 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '6526521e324c615ec94f2139',
    index: 1,
    guid: 'c7bc5278-65a5-4c51-8d0f-38b86c2e049b',
    isActive: false,
    balance: '$2,503.84',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'brown',
    name: 'Parsons Wade',
    gender: 'male',
    company: 'VISALIA',
    email: 'parsonswade@visalia.com',
    phone: '+1 (966) 513-2829',
    address: '444 Cadman Plaza, Day, Delaware, 640',
    about:
      'Et non laboris Lorem commodo ea cillum qui ipsum in sint. Dolore proident laboris irure ex ad laboris pariatur voluptate culpa deserunt elit. Nulla nisi pariatur adipisicing mollit adipisicing aliquip ex ad eu. Aute officia ad minim nulla aliqua velit ut elit est nisi.\r\n',
    registered: '2017-03-08T10:54:27 -02:00',
    latitude: -80.661238,
    longitude: -49.467016,
    tags: ['sit', 'amet', 'do', 'Lorem', 'dolore', 'anim', 'fugiat'],
    friends: [
      {
        id: 0,
        name: 'Maritza Harding',
      },
      {
        id: 1,
        name: 'Vilma Miles',
      },
      {
        id: 2,
        name: 'Golden Wheeler',
      },
    ],
    greeting: 'Hello, Parsons Wade! You have 7 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '6526521ef519625f81767b70',
    index: 2,
    guid: '585a4169-df28-4345-9c12-3a200879bfe3',
    isActive: false,
    balance: '$3,013.07',
    picture: 'http://placehold.it/32x32',
    age: 30,
    eyeColor: 'blue',
    name: 'Elvira Austin',
    gender: 'female',
    company: 'MONDICIL',
    email: 'elviraaustin@mondicil.com',
    phone: '+1 (906) 428-3109',
    address: '154 Menahan Street, Manitou, Marshall Islands, 4851',
    about:
      'Consequat consequat magna aliqua ipsum nisi officia sit ad aliqua eu culpa officia qui. Eiusmod ex qui commodo magna non id. Velit eiusmod officia adipisicing culpa.\r\n',
    registered: '2014-08-20T04:40:58 -03:00',
    latitude: -35.85177,
    longitude: 124.728449,
    tags: [
      'commodo',
      'culpa',
      'sint',
      'reprehenderit',
      'minim',
      'voluptate',
      'aliqua',
    ],
    friends: [
      {
        id: 0,
        name: 'Cathleen Wilkinson',
      },
      {
        id: 1,
        name: 'Fry Ruiz',
      },
      {
        id: 2,
        name: 'Hammond Barker',
      },
    ],
    greeting: 'Hello, Elvira Austin! You have 1 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '6526521e9696c755b7b18243',
    index: 3,
    guid: '7a4c4394-7359-49dd-bace-f7bbd56c4436',
    isActive: false,
    balance: '$2,026.97',
    picture: 'http://placehold.it/32x32',
    age: 32,
    eyeColor: 'blue',
    name: 'Boyle Ortega',
    gender: 'male',
    company: 'VICON',
    email: 'boyleortega@vicon.com',
    phone: '+1 (863) 446-2026',
    address: '909 McKinley Avenue, Bynum, West Virginia, 1825',
    about:
      'Veniam magna id elit et laborum Lorem officia ea anim sint mollit. Proident laborum dolor pariatur magna eiusmod anim culpa consectetur pariatur. Adipisicing elit tempor aliquip Lorem laborum amet Lorem duis sunt amet velit non laboris.\r\n',
    registered: '2022-08-05T03:09:49 -03:00',
    latitude: 80.320649,
    longitude: 22.927373,
    tags: ['anim', 'minim', 'esse', 'dolor', 'eiusmod', 'eu', 'est'],
    friends: [
      {
        id: 0,
        name: 'Glenn Morales',
      },
      {
        id: 1,
        name: 'Gloria Stafford',
      },
      {
        id: 2,
        name: 'Melva Gentry',
      },
    ],
    greeting: 'Hello, Boyle Ortega! You have 5 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '6526521e4264052af13f40ec',
    index: 4,
    guid: '090187ac-bac5-40d2-a26d-38dd20d7eeb8',
    isActive: false,
    balance: '$3,703.28',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'blue',
    name: 'Torres Booth',
    gender: 'male',
    company: 'ANDRYX',
    email: 'torresbooth@andryx.com',
    phone: '+1 (904) 534-3985',
    address: '885 Flatbush Avenue, Nogal, South Carolina, 8436',
    about:
      'Laborum enim nisi aute magna occaecat laboris dolor id voluptate veniam voluptate quis incididunt. Occaecat occaecat et nulla in Lorem. Tempor consequat occaecat fugiat anim laboris ad labore. Amet occaecat Lorem enim sint in sint culpa veniam labore eu occaecat. Ex pariatur adipisicing ad et cupidatat aute cupidatat enim adipisicing velit magna exercitation tempor.\r\n',
    registered: '2019-01-20T02:35:52 -02:00',
    latitude: 66.512554,
    longitude: 169.288529,
    tags: [
      'duis',
      'dolore',
      'eiusmod',
      'ullamco',
      'et',
      'proident',
      'pariatur',
    ],
    friends: [
      {
        id: 0,
        name: 'Osborn Barber',
      },
      {
        id: 1,
        name: 'Chandra Walls',
      },
      {
        id: 2,
        name: 'Rosemary Walton',
      },
    ],
    greeting: 'Hello, Torres Booth! You have 3 unread messages.',
    favoriteFruit: 'strawberry',
  },
];
